name: Build App

on:
  push:
    # Trigger only for main branch.
    branches: [ main, master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Gradle Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Get the app source
      - name: Get the source
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Set up Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Make gradlew executable and fix line endings
      - name: Fix gradlew permissions and line endings
        run: |
          chmod +x ./gradlew
          dos2unix ./gradlew || true

      # Clean and compile the apk
      - name: Clean and Generate Debug APK
        run: |
          ./gradlew clean assembleDebug --warning-mode=all --stacktrace

      # Upload the action artifact
      - name: Upload Debug APK (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
